name: ryantaylor
favicon: null
layout_spectrum: 1
typography_spectrum: 0.002515157451853156
title: Neo Soul Jazz Artist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040412'
    - '#48332c'
    - '#b41c3c'
    - '#bf6a5a'
    - '#ffde9f'
  brandStrength: 0.1875
  lightness: 0.3125
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
