name: ryantaylor
favicon: null
layout_spectrum: 0.00086
typography_spectrum: 0.64532
title: Neo Soul Jazz Artist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040011'
    - '#ffebae'
    - '#365558'
    - '#6f162e'
    - '#ff375d'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
