name: ryantaylor
favicon: null
layout_spectrum: 0.4615
typography_spectrum: 0.5552
title: dsgnr stff
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eeeeee'
    - '#000000'
    - '#5e5e5e'
    - '#959595'
    - '#bc3c4b'
  brandStrength: 0.75
  lightness: 0.4032258
  saturation: 0.5985663
  rhythmicContrast: 0.6433692
purpose: []
