title: dsgnr stff
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5985663
  brandStrength: 0.75
  rhythmicContrast: 0.6433692
  brandColors:
    - '#eeeeee'
    - '#000000'
    - '#5e5e5e'
    - '#959595'
    - '#bc3c4b'
  lightness: 0.4032258
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: ryantaylor
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5552
layout_spectrum: 0.8082438
