name: ryantaylor
favicon: null
layout_spectrum: 0.8617025746498257
typography_spectrum: 0.002515157451853156
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 1
  lightness: 0.8752991461660713
  saturation: 0.4423807698767632
  rhythmicContrast: 0.25
purpose: []
